networks:
  app-network:
    driver: bridge
    
services:
  nova-webapi:
    image: ${DOCKER_REGISTRY-}nova-webapi
    container_name: nova-webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    expose:
      - 80
    ports:
      - "8080:80"
    links:
      - nova-sql-server
    networks:
      - app-network
    depends_on:
      - nova-sql-server
        

  nova-sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    hostname: mssql
    container_name: nova-sql-server
    expose:
      - 1433
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pMA63033n6tF
    networks:
      - app-network