using Domain.SharedKernel;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Infrastructure.Extensions;

internal static class EntityTypeBuilderExtensions
{
    internal static void ConfigureBaseEntity<TEntity>(this EntityTypeBuilder<TEntity> builder)
        where TEntity : Entity
    {
        // Sets the primary key for the entity to the ID property.
        builder
            .HasKey(entity => entity.Id);

        // Configures the ID property to be required (NOT NULL) and not generated by the database.
        builder
            .Property(entity => entity.Id)
            .IsRequired()
            .ValueGeneratedNever();
    }
}